version: '3.7'

services:
  nginx:
    image: nginx
    deploy: 
      replicas: 3
      placement:
        constraints: [node.role == worker]
      restart_policy:
        condition: on-failure
        max_attempts: 2
    environment:
      SERVICE_PORTS: 80
    networks:
      - web
  proxy:
    image: dockercloud/haproxy
    depends_on:
      - nginx
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports: # -p option, attached to ingress network
      - "80:80"
    networks: # backend network -> nginx containers
      - web
    deploy:
      mode: global
      placement:
        constraints: [node.role==manager]


networks:
  web:
    external: true
